# Generated by Django 3.1 on 2020-11-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partquestion',
            name='parttitle',
            field=models.CharField(max_length=1500),
        ),
    ]
