# Generated by Django 3.1 on 2020-11-29 17:40

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('secondapp', '0002_auto_20201129_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answerquestion',
            options={'verbose_name': 'Javob', 'verbose_name_plural': 'Javoblar'},
        ),
        migrations.AlterModelOptions(
            name='contact_us',
            options={'verbose_name': 'Aloqa', 'verbose_name_plural': 'Biz bilan Aloqa'},
        ),
        migrations.AlterModelOptions(
            name='partquestion',
            options={'verbose_name': 'Savol Bo`limi', 'verbose_name_plural': 'Test Bo`limlari Nomi'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Savol', 'verbose_name_plural': 'Savollar'},
        ),
        migrations.AlterModelOptions(
            name='question_lang',
            options={'verbose_name': 'Til Qo`sish', 'verbose_name_plural': 'Tillar Nomi (Test yechish uchun)'},
        ),
        migrations.AlterModelOptions(
            name='register',
            options={'verbose_name': 'Ro`yxatga olish', 'verbose_name_plural': 'Ro`yxatdan O`tganlar'},
        ),
        migrations.AlterModelOptions(
            name='result',
            options={'verbose_name': 'Natija', 'verbose_name_plural': 'Natijalar'},
        ),
        migrations.RemoveField(
            model_name='partquestion',
            name='digital',
        ),
        migrations.AlterField(
            model_name='answerquestion',
            name='ansa',
            field=models.CharField(max_length=300, null=True, verbose_name='Ishtirokchi Javobi'),
        ),
        migrations.AlterField(
            model_name='answerquestion',
            name='is_true',
            field=models.BooleanField(blank=True, verbose_name='To`gri/Xato'),
        ),
        migrations.AlterField(
            model_name='answerquestion',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondapp.question', verbose_name='Savol'),
        ),
        migrations.AlterField(
            model_name='answerquestion',
            name='question_langid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondapp.question_lang', verbose_name='Til'),
        ),
        migrations.AlterField(
            model_name='answerquestion',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Jo`natilgan Sana'),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='contact_number',
            field=models.CharField(blank=True, max_length=250, unique=True, verbose_name='Telefon Nomer'),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='E-pochta'),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='message',
            field=models.TextField(verbose_name='Xabar'),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='contact_us',
            name='subject',
            field=models.CharField(max_length=250, verbose_name='Mavzu'),
        ),
        migrations.AlterField(
            model_name='partquestion',
            name='partdesc',
            field=models.CharField(blank=True, max_length=1500, verbose_name='Bo`lim Tavsifi'),
        ),
        migrations.AlterField(
            model_name='partquestion',
            name='parttitle',
            field=models.CharField(max_length=1500, verbose_name='Savollar Bo`limi'),
        ),
        migrations.AlterField(
            model_name='partquestion',
            name='question_langid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondapp.question_lang', verbose_name='Til'),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, max_length=250, verbose_name='To`g`ri Javob'),
        ),
        migrations.AlterField(
            model_name='question',
            name='partquestion_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondapp.partquestion', verbose_name='Savol Bo`limi'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qitem1',
            field=models.CharField(blank=True, max_length=250, verbose_name='Variant 1'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qitem2',
            field=models.CharField(blank=True, max_length=250, verbose_name='Variant 2'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qitem3',
            field=models.CharField(blank=True, max_length=250, verbose_name='Variant 3'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qitem4',
            field=models.CharField(blank=True, max_length=250, verbose_name='Variant 4'),
        ),
        migrations.AlterField(
            model_name='question',
            name='qname',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Savol'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_langid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondapp.question_lang', verbose_name='Til'),
        ),
        migrations.AlterField(
            model_name='question_lang',
            name='audio',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Audio'),
        ),
        migrations.AlterField(
            model_name='question_lang',
            name='desc',
            field=models.CharField(blank=True, max_length=250, verbose_name='Tavsifi'),
        ),
        migrations.AlterField(
            model_name='question_lang',
            name='end_time',
            field=models.DateTimeField(verbose_name='Yakunlanish Vaqti'),
        ),
        migrations.AlterField(
            model_name='question_lang',
            name='name_lang',
            field=models.CharField(max_length=250, verbose_name='Til Nomi'),
        ),
        migrations.AlterField(
            model_name='question_lang',
            name='start_time',
            field=models.DateTimeField(verbose_name='Boshlanish Vaqti'),
        ),
        migrations.AlterField(
            model_name='register',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='O`zim haqimda'),
        ),
        migrations.AlterField(
            model_name='register',
            name='added_on',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Qo`shilgan Sana'),
        ),
        migrations.AlterField(
            model_name='register',
            name='balance',
            field=models.IntegerField(default=False, verbose_name='Balans'),
        ),
        migrations.AlterField(
            model_name='register',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Shahar'),
        ),
        migrations.AlterField(
            model_name='register',
            name='contact_number',
            field=models.IntegerField(verbose_name='Telefon Nomer'),
        ),
        migrations.AlterField(
            model_name='register',
            name='contact_number2',
            field=models.CharField(max_length=250, verbose_name='Shifrlangan T.Nomer'),
        ),
        migrations.AlterField(
            model_name='register',
            name='dateofbirth',
            field=models.DateField(verbose_name='Tug`ilgan Sana'),
        ),
        migrations.AlterField(
            model_name='register',
            name='gender',
            field=models.CharField(default='Male', max_length=250, null=True, verbose_name='Jins'),
        ),
        migrations.AlterField(
            model_name='register',
            name='occupation',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Kasb'),
        ),
        migrations.AlterField(
            model_name='register',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/%Y/%m/%d', verbose_name='Profil rasm'),
        ),
        migrations.AlterField(
            model_name='register',
            name='provin',
            field=models.CharField(blank=True, choices=[('Andijon', 'Andijon'), ('Buxoro', 'Buxoro'), ('Fargʻona', 'Fargʻona'), ('Jizzax', 'Jizzax'), ('Xorazm', 'Xorazm'), ('Namangan', 'Namangan'), ('Navoiy', 'Navoiy'), ('Qashqadaryo', 'Qashqadaryo'), ('Qoraqalpogʻiston', 'Qoraqalpogʻiston'), ('Samarqand', 'Samarqand'), ('Sirdaryo', 'Sirdaryo'), ('Surxondaryo', 'Surxondaryo'), ('Qashqadaryo', 'Qashqadaryo'), ('Toshkent', 'Toshkent')], max_length=200, null=True, verbose_name='Viloyat'),
        ),
        migrations.AlterField(
            model_name='register',
            name='sert_id',
            field=models.CharField(max_length=10, null=True, unique=True, verbose_name='Sertifikat Nomer'),
        ),
        migrations.AlterField(
            model_name='register',
            name='state',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Davlat'),
        ),
        migrations.AlterField(
            model_name='register',
            name='training_center',
            field=models.CharField(max_length=250, verbose_name='O`quv Markazi'),
        ),
        migrations.AlterField(
            model_name='register',
            name='update_on',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Yangilangan Sana'),
        ),
        migrations.AlterField(
            model_name='result',
            name='correct_answers',
            field=models.CharField(max_length=100, verbose_name='To`g`ri Javoblar Soni'),
        ),
        migrations.AlterField(
            model_name='result',
            name='place_number',
            field=models.CharField(blank=True, max_length=250, verbose_name='Ishtirokchi Reytingi(Viloyat)'),
        ),
        migrations.AlterField(
            model_name='result',
            name='place_number_country',
            field=models.CharField(blank=True, max_length=250, verbose_name='Ishtirokchi Reytingi(Respublika)'),
        ),
        migrations.AlterField(
            model_name='result',
            name='question_langid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondapp.question_lang', verbose_name='Til'),
        ),
        migrations.AlterField(
            model_name='result',
            name='register_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondapp.register', verbose_name='Ishtirokchi'),
        ),
        migrations.AlterField(
            model_name='result',
            name='result',
            field=models.CharField(max_length=250, verbose_name='Ishtirokchi To`plagan Bal'),
        ),
        migrations.AlterField(
            model_name='result',
            name='total_questions',
            field=models.CharField(max_length=100, verbose_name='Umumiy Savollar Soni'),
        ),
        migrations.AlterField(
            model_name='result',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
    ]
